[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mt-training"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = ["ny-feoko-shared"]

[tool.hatch.build.targets.wheel]
packages = ["src/mt_training"]
