[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ny-feoko-shared"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["ny_feoko_shared"]
